---
kodi_packages:
  - acl
  - ca-certificates
  - cec-utils
  - kodi
  - kodi-inputstream-adaptive
  - kodi-repository
  - kodi-visualization-spectrum
  - kodi-vfs-rar
  - mesa-utils
  - pulseaudio
  - samba-common-bin
