---

- name: Disable password based login with SSH
  ansible.builtin.lineinfile:
    regexp: '^#PasswordAuthentication yes'
    line: "PasswordAuthentication no"
    path: /etc/ssh/sshd_config

- name: Reload sshd service
  ansible.builtin.systemd:
    name: sshd
    state: reloaded
