---
- name: Disable password based login with SSH
  ansible.builtin.lineinfile:
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
    path: /etc/ssh/sshd_config.d/ssh-hardening.conf
    mode: "0600"
    create: true

- name: Reload sshd service
  ansible.builtin.systemd:
    name: ssh
    state: reloaded
