---

- name: Install DNSMASQ
  ansible.builtin.package:
    name: dnsmasq
    update_cache: true
  notify: Reload systemd

- name: Enable DNSMASQ on boot
  ansible.builtin.systemd:
    name: dnsmasq
    state: started
    enabled: true

- name: Enable PXE DHCP Options for DNSMASQ
  become: true
  ansible.builtin.template:
    src: tftp.conf.j2
    dest: /etc/dnsmasq.d/tftp.conf
    owner: root
    group: root
    mode: '0644'
  tags: tftp
  notify: Restart dnsmasq
